diplom:
  db:
    name: 'diplomDb'

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web.exposure:
      include: '*'
spring:
  application:
    name: diplom

  cloud:
    consul:
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${random.value}
#    config:
#      enabled: true
#      watch:
#        enabled: true

server:
  port: 8100

logging:
  level:
    org.springframework.web: ERROR
    com.kurenchuksergey: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ./app.log